services:
  - type: web
    name: fancy-font-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: TOKEN
        sync: false
      - key: PORT
        value: 10000 